spring.datasource.url=jdbc:postgresql://URL_NUBE:5432/econexo_prod
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false